Centering the Event Cards on the events page
Will-Hsu/cses_webdev pull request #104
Opened 2024-01-17 20:15 UTC by ssyquia

2024-01-19 05:09 UTC, joycellu commented
I fixed the margin below the filtering button "2023" above the event cards.

Below are screenshots of the page on desktop, iPad, and iPhone 12 Pro:
<img width="1512" alt="Screen Shot 2024-01-18 at 9 04 58 PM" src="https://github.com/Will-Hsu/cses_webdev/assets/114626933/be5f07fb-8b3d-4941-ae04-90f317ac799b">
<img width="1190" alt="Screen Shot 2024-01-18 at 9 05 36 PM" src="https://github.com/Will-Hsu/cses_webdev/assets/114626933/749ecd1f-083a-4f85-b4eb-a09671fa28be">
<img width="1190" alt="Screen Shot 2024-01-18 at 9 05 19 PM" src="https://github.com/Will-Hsu/cses_webdev/assets/114626933/985c308b-11c9-4ddc-a599-3702d0dfe1e9">

2024-01-26 01:36 UTC, Will-Hsu requested changes
Bug -- We don't want cards to be centered in desktop view.

2024-02-15 00:13 UTC, joycellu commented
2024/2/14
- Added the "2024" filter button for past events (made it so that the buttons are dynamically generated); made sure events are displayed correctly when the corresponding year button is clicked on.
- Enhanced the UI of event cards section (specifically margins below the filtering buttons & long titles).
<img width="601" alt="Screen Shot 2024-02-13 at 2 48 18 PM" src="https://github.com/Will-Hsu/cses_webdev/assets/114626933/c6380c55-55a1-40c7-b320-951ec31ef1f8">

<img width="1512" alt="Screen Shot 2024-02-13 at 2 49 17 PM" src="https://github.com/Will-Hsu/cses_webdev/assets/114626933/6176e423-af8b-4087-9a15-de13e5154e1f">

2024-02-16 01:04 UTC, Will-Hsu approved these changes

2024-02-16 01:04 UTC, merged